version: '3.1'

services:

  wordpress:
    image: wordpress:php7.4-fpm
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./wordpress:/var/www/html
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./wp-content/plugins:/var/www/html/wp-content/plugins

  nginx:
    depends_on:
      - wordpress
    image: nginx:1.19
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./contrib/docker-compose/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html