version: '3.1'

services:

  wordpress:
    image: wordpress:php7.4-fpm
    restart: unless-stopped
    env_file: .env
    environment:
      WORDPRESS_CONFIG_EXTRA: |
          define( 'WP_SITEURL', '${SITE_URL}' );
          define( 'WP_HOME', '${SITE_URL}' );
          define( 'WP_DEBUG', ${WP_DEBUG} );
    volumes:
      - ./wordpress:/var/www/html
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./contrib/docker-compose/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  nginx:
    depends_on:
      - wordpress
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./contrib/docker-compose/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
